SELECT * 
FROM (
    SELECT i_name, i_date
    FROM (
        SELECT ANIMAL_INS.NAME AS i_name, ANIMAL_INS.DATETIME AS i_date, ANIMAL_OUTS.DATETIME As o_date
        FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
        ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
        )
    WHERE o_date is NULL
    ORDER BY i_date
    )
WHERE ROWNUM <=3


SELECT *
FROM (SELECT a.NAME, a.DATETIME
      FROM ANIMAL_INS a LEFT JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
      WHERE b.ANIMAL_ID IS NULL
      ORDER BY a.DATETIME
     )
WHERE ROWNUM < 4;